name: cron

on:
  push:
    branches:
      - master
  schedule:
    - cron: "25 1 * * 1"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Metrics embed full-year calendar
        uses: lowlighter/metrics@v3.34
        with:
          filename: metrics.plugin.isocalendar.fullyear.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
      - name: 🍽️ Get working copy
        uses: actions/checkout@master
        with:
          fetch-depth: 1                                                                 
      - name: 🐍 Set up Python 3.8                               
        uses: actions/setup-python@v2                             
        with:                                 
          python-version: '3.8'                                                   
      - name: 💿 Install feedparser pytz datetime                           
        run: pip install feedparser pytz datetime
      - name: 🍳 Update README
        run: |
          cd ${GITHUB_WORKSPACE}/src/
          python readme.py
      - name: 🚀 Deploy
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git add .
          git commit -am "feat(auto generate): Updated content"
          git push --all -f https://${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git
